fix omitted FilterRules in get_bucket_notification response
minio/minio-py pull request #1036
Opened 2020-11-30 13:52 UTC by plankthom

The 6.0.xx releases of minio-py do not include any filter rules in the `get_bucket_notification` response. 

This fix resolves the issues in the release branch, and adds a test case for the issue.

2020-11-30 13:58 UTC, balamurugana requested changes
Please send fix to `master` branch, Note that it was refactored in the branch.

2020-11-30 14:39 UTC, plankthom commented
@balamurugana As I don't know the release planning of minio-py, i fixed it on the latest release, so that I could continue my development. PR #1037 validates that this is solved on master.  
Please consider this fix if master (7.0.0) is not going to be release any time soon ...

2020-12-03 08:46 UTC, kannappanr commented
@plankthom We are planning to make a release soon. I don't have an exact date, but hopefully soon

2020-12-03 09:03 UTC, ebozduman commented
@plankthom,
Could you close the PR as a new official release that will address your issue is coming soon?

2020-12-03 14:01 UTC, plankthom commented
Ok, closing this PR, this will force me to use the unsupported release that i created at https://github.com/waylayio/minio-py/releases/tag/6.0.3_waylay01 ...

2020-12-03 14:02 UTC, closed without merging