Add MinIO admin API support.
minio/minio-py pull request #1076
Opened 2021-02-02 19:06 UTC by balamurugana

2021-02-02 19:08 UTC, harshavardhana requested changes

2021-02-02 19:08 UTC, harshavardhana commented on minio/minioadmin.py
> +    """Minio Admin wrapper using Minio Client (mc) tool."""
```suggestion
    """MinIO Admin wrapper using MinIO Client (mc) tool."""
```

2021-02-03 06:15 UTC, kannappanr commented on minio/minioadmin.py
> +# (C) 2020 MinIO, Inc.
```suggestion
# (C) 2021 MinIO, Inc.
```

2021-02-04 23:14 UTC, krisis commented
@balamurugana it would be useful to have a README introducing this package and a couple of simple examples to demonstrate usage like we have for the minio package .

2021-02-04 23:14 UTC, krisis approved these changes

2021-02-12 05:27 UTC, harshavardhana approved these changes

2021-02-12 05:28 UTC, harshavardhana approved these changes

2021-02-12 05:33 UTC, kannappanr approved these changes

2021-02-12 05:33 UTC, merged

2021-11-23 13:23 UTC, torbendury commented
Is there any documentation available on how to use this `MinioAdmin` object?

2021-11-23 13:35 UTC, balamurugana commented
@torbendury If you know how to use `mc admin` command line, you can directly refer https://github.com/minio/minio-py/blob/master/minio/minioadmin.py

2021-11-27 12:32 UTC, torbendury commented
@balamurugana That's what I did, but searching through function definitions doesn't feel right. At least a refer on the Python SDK docs to this file would be great, so that other who wonder about the admin API don't wonder how to access it.