Fix legacy key name in retrieve
minio/minio-py pull request #1090
Opened 2021-03-02 13:57 UTC by vonera

Keep both the old format and the new format key to support older and the current mc config files

2021-03-02 14:08 UTC, balamurugana requested changes

2021-03-02 14:08 UTC, balamurugana commented on minio/credentials/providers.py
> +            creds = config.get(key).get(self._alias)
Use more pythonic like below
```py
diff --git a/minio/credentials/providers.py b/minio/credentials/providers.py
index 1447a59..7765e38 100644
--- a/minio/credentials/providers.py
+++ b/minio/credentials/providers.py
@@ -307,13 +307,14 @@ class MinioClientConfigProvider(Provider):
         try:
             with open(self._filename) as conf_file:
                 config = json.load(conf_file)
-            if not config.get("hosts"):
+            aliases = config.get("hosts") or config.get("aliases")
+            if not aliases:
                 raise ValueError(
                     "invalid configuration in file {0}".format(
                         self._filename,
                     ),
                 )
-            creds = config.get("hosts").get(self._alias)
+            creds = aliases.get(self._alias)
             if not creds:
                 raise ValueError(
                     (
```

2021-03-02 14:30 UTC, vonera reviewed
changed as suggested

2021-03-02 15:51 UTC, balamurugana approved these changes

2021-03-02 16:20 UTC, balamurugana approved these changes

2021-03-11 07:15 UTC, kannappanr approved these changes

2021-03-11 07:15 UTC, merged