HOME env var does not exists on windows
minio/minio-py pull request #1175
Opened 2022-01-31 17:13 UTC by nfioraio-ec

AWSConfigProvider and MinioClientConfigProvider look for config files under home directory, which is retrieved as `os.environ.get("HOME")`. However, under Windows this env var does not exists and the `os.path.join` raises a TypeError. Fixed by getting `os.environ.get("UserProfile")` or `str(Path.home())` as a last resort.

2022-01-31 22:52 UTC, balamurugana requested changes

2022-01-31 22:52 UTC, balamurugana commented on minio/credentials/providers.py
> +                str(Path.home()),
Have a function to return home directory instead of repeating the logic.

2022-01-31 22:52 UTC, balamurugana commented on minio/credentials/providers.py
> +        from pathlib import Path
Please fix github CI error.

2022-01-31 23:21 UTC, balamurugana reviewed
Please fix CI error

2022-01-31 23:50 UTC, balamurugana approved these changes

2022-02-01 01:38 UTC, harshavardhana approved these changes

2022-02-01 01:38 UTC, merged