Add AssumeRoleWithCertificate credential provider.
minio/minio-py pull request #1182
Opened 2022-02-28 14:13 UTC by balamurugana

Signed-off-by: Bala.FA <bala@minio.io>

2022-02-28 17:11 UTC, harshavardhana commented
@balamurugana looks like you didn't test this with MinIO. You need to provide provisions for client.crt and client.key 

You haven't added any API that takes client certs. 

minio-go API takes tls.Certificate which is a private and public key certificate - https://pkg.go.dev/crypto/tls#Certificate

2022-02-28 17:45 UTC, harshavardhana approved these changes

2022-02-28 20:10 UTC, harshavardhana requested changes

2022-02-28 20:10 UTC, harshavardhana commented on examples/minio_with_certificate_identity_provider.py
> +# (C) 2020 MinIO, Inc.
should be 2022? @balamurugana

2022-03-01 04:13 UTC, balamurugana commented
Tested the PR using self-signed certificates with ignoring certificate check using custom HTTP client.

2022-03-03 04:53 UTC, harshavardhana approved these changes

2022-03-03 04:53 UTC, merged