Add verify_ssl flag to main api class constructor
minio/minio-py pull request #1267
Opened 2023-02-26 22:48 UTC by walnuttiger8

inspired by `verify` flag in requests library https://github.com/psf/requests/blob/main/requests/sessions.py#L515

2023-02-27 03:38 UTC, balamurugana requested changes

2023-02-27 03:38 UTC, balamurugana commented on minio/api.py
> +                 verify_ssl=True):
Name this arg as `cert_check`

2023-02-28 00:50 UTC, balamurugana approved these changes

2023-05-20 18:11 UTC, harshavardhana approved these changes

2023-05-20 18:12 UTC, merged