Update deprecated mc admin policy commands
minio/minio-py pull request #1277
Opened 2023-04-25 21:23 UTC by pbrw

[`mc admin policy add/set/unset` are now deprecated](https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-policy.html#command-mc.admin.policy)
I updated them with acordingly.

2023-04-26 03:46 UTC, balamurugana requested changes

2023-04-26 03:46 UTC, balamurugana commented on minio/minioadmin.py
> +                    ("--user" if user else "--group"), (user or group),
Please remove brackets around `(user or group)`

2023-04-26 03:46 UTC, balamurugana commented on minio/minioadmin.py
> +                    ("--user" if user else "--group"), (user or group),
Please remove brackets around `(user or group)`

2023-04-26 06:19 UTC, balamurugana submitted a review, later dismissed

2023-05-20 18:11 UTC, harshavardhana approved these changes

2023-05-21 02:24 UTC, balamurugana approved these changes

2023-05-21 02:51 UTC, merged