add type hint for `Minio.__init__`
minio/minio-py pull request #1299
Opened 2023-08-30 04:50 UTC by trim21

2023-08-30 23:55 UTC, balamurugana requested changes

2023-08-30 23:55 UTC, balamurugana commented on minio/api.py
> +    def __init__(
Like https://github.com/minio/minio-py/pull/1298/files#diff-4deb4dada12fa30d829f5d6b460cd65f36cc6b6d1ff26f513fcc4ef9e0783abbR28-R31, define all members here too.

2023-08-31 11:28 UTC, trim21 commented on minio/api.py
> +    def __init__(
done

2023-08-31 13:06 UTC, trim21 commented on minio/api.py
> +    _provider: StaticProvider | Provider | None
```suggestion
    _provider: Provider | None
```

2023-08-31 13:10 UTC, balamurugana approved these changes

2023-09-24 13:09 UTC, harshavardhana submitted a review, later dismissed

2023-09-24 13:23 UTC, balamurugana requested changes
Fix the CI failure

2023-09-24 13:36 UTC, balamurugana requested changes
Remove all unnecessary diffs

2023-09-24 13:42 UTC, trim21 commented
> Remove all unnecessary diffs

already done

2023-09-24 13:55 UTC, balamurugana approved these changes

2023-09-24 15:41 UTC, balamurugana requested changes
Resolve the conflict.

2023-09-25 04:19 UTC, balamurugana approved these changes

2023-09-25 05:52 UTC, harshavardhana approved these changes

2023-09-25 05:52 UTC, merged