list_objects can filter by tags
minio/minio-py pull request #1381
Opened 2023-12-27 20:55 UTC by angrybat

This adds the ability to filter all Objects returned by the list_objects method by the tags on the object. 

This adds the tags property to the Object class which can be set in the constructor of the class. This defaults to an empty Tags class. 

The http response already contains the tags in the xml response under the text in the "UserTags" key. The fromxml method has been modified to set the tags to a populated version of the Tags class. This used the added Tags.object_from_user_tags_text method.

The Tags.object_from_user_tags_text method is a new method that creates a Tags class instance for Objects from a string in the format "key1=value1&key2=value2". This is the format the tags are in the text of the "UserTags" key.

Another method has been added called Tags.object_from_dict. This creates an instance for Objects from a dictionary. This is currently only used in the tests to create an instance of the Tags class but this can be a method that is imported to pass to the new tags property on the list_objects method.  

The list_objects method has been modified to pass an optional tags property, this defaults to None. When the property is None then the Objects returned are not filtered by tags at all. If the tags property is set to an instance of the Tags class then it will filter the list of Objects that have tags that match. This works by an exact match of each key, i.e if the following key values are passed key1=value1, key2=value2 then only Objects with both key1=value1 and key2=value2 will be returned. 

Examples showing how list_objects can be used to filter based on tags have been added to docs/api.md and examples/list_objects.py.

2023-12-28 01:46 UTC, balamurugana requested changes
Filtering objects by any parameter should be done outside of `minio-py`. Please keep the PR focusing on adding `UserTags` support.

2023-12-28 10:47 UTC, angrybat commented
@balamurugana out of interest how come filtering by UserTags should be done outside of minio-py? 

The list_objects function has a prefix parameter that allows you to filter by path. How come that is different to filtering by UserTags?

The filtering I have added here is optional. So the original functionality of the function is preserved.

2023-12-28 10:50 UTC, balamurugana commented
> @balamurugana out of interest how come filtering by UserTags should be done outside of minio-py?
> 
> The list_objects function has a prefix parameter that allows you to filter by path. How come that is different to filtering by UserTags?
> 
> The filtering I have added here is optional. So the original functionality of the function is preserved.

Filtering by `prefix` and other parameters are done at server side whereas `UserTags` filtering is done at client side in this PR which we don't want.

2023-12-28 16:39 UTC, balamurugana requested changes

2023-12-28 16:39 UTC, balamurugana commented on minio/datatypes.py
> +            tags: Tags = Tags.new_object_tags(),
It should be `tags: Tags | None = None`

2023-12-28 16:39 UTC, balamurugana commented on minio/commonconfig.py
> +    def object_from_user_tags_text(cls: Type[A], string: str | None) -> A:
Remove this method and move the logic into https://github.com/minio/minio-py/pull/1381/files#diff-321a5d1087d9a70eb00a39c6bfe8b7295ff787da4efe97f7fe7fd16aed5c2df3R265

2023-12-29 15:36 UTC, balamurugana requested changes

2023-12-29 15:36 UTC, balamurugana commented on minio/datatypes.py
> +                tags[key] = value
```suggestion
        tags: Tags | None = None
        if tag_text:
            tags = Tags.new_object_tags()
            tags.update([tokens.split("=") for tokens in tag_text.split("&")])
```

2023-12-30 02:03 UTC, balamurugana submitted a review, later dismissed

2023-12-30 02:05 UTC, balamurugana commented on minio/datatypes.py
> +            tags.update([tokens.split("=") for tokens in tag_text.split("&")])
```suggestion
            tags.update([tokens.split("=") for tokens in tags_text.split("&")])
```

2023-12-30 02:08 UTC, balamurugana commented on minio/datatypes.py
> +        if tag_text:
```suggestion
        if tags_text:
```

2023-12-30 02:14 UTC, balamurugana commented on minio/datatypes.py
> +            tags.update([tokens.split("=") for tokens in tags_text.split("&")])
```suggestion
            tags.update(
                [tuple(tokens.split("=")) for tokens in tags_text.split("&")],
            )
```

2023-12-30 02:32 UTC, balamurugana commented on minio/datatypes.py
> +                [tuple(tokens.split("=")) for tokens in tags_text.split("&")],
```suggestion
                cast(
                    List[Tuple[Any, Any]],
                    [tokens.split("=") for tokens in tags_text.split("&")],
                ),
```

2023-12-30 02:35 UTC, balamurugana requested changes
import `List`, `Tuple`, `Any` at line no. 30

2023-12-30 12:12 UTC, balamurugana approved these changes

2024-01-13 15:28 UTC, angrybat commented
Can I get a second review please

2024-01-13 17:36 UTC, harshavardhana approved these changes

2024-01-13 17:42 UTC, merged