Add cert_check kwarg to Minio class docs
minio/minio-py pull request #1385
Opened 2023-12-29 02:57 UTC by paytonward6

Adds missing `cert_check` kwarg to the Minio class docs

2023-12-29 04:46 UTC, balamurugana requested changes

2023-12-29 04:46 UTC, balamurugana commented on docs/API.md
> +| `cert_check`    | _bool_                            | (Optional) Flag to indicate if SSL certificate of S3 endpoint should verified.   |
```suggestion
| `cert_check`    | _bool_                            | (Optional) Flag to check on server certificate for HTTPS connection.   |
```

2023-12-30 02:04 UTC, balamurugana approved these changes

2023-12-30 04:12 UTC, harshavardhana approved these changes

2023-12-30 04:12 UTC, merged