Add user svcacct features
minio/minio-py pull request #1399
Opened 2024-02-07 17:09 UTC by Alveel

Added the missing functions to manage service accounts with this library.

WIP because `service_account_update` is for some reason not working yet, I keep getting the following error:

`minio.error.MinioAdminException: admin request failed; Status: 426, Body: {"Code":"XMinioAdminVersionMismatch","Message":"This 'admin' API is not supported by server in 'mode-server-distributed-xl'","Resource":"/minio/admin/v3/update-service-account","RequestId":"","HostId":""}`

2024-02-12 10:59 UTC, Alveel commented
Ready for review!

2024-02-15 13:54 UTC, Alveel commented
@balamurugana did you have a chance to take a peek?

2024-02-16 22:42 UTC, Alveel commented
Some of it is not the prettiest, I welcome suggestions and improvements.

2024-02-22 01:58 UTC, balamurugana requested changes

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_info(self, access_key):
1. Add typing
2. The method can be renamed as `get_service_account_info`

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_list(self, user: str):
1. Add typing
2. The method can be renamed to `list_service_account`

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +                            secret_key: str = "",
1. access/secret key args should be `access_key: str | None = None` and `secret_key: str | None = None`
2. Add typing to return value

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +            raise ValueError("access_key must be provided if secret_key is "
Just do
```py
if (access_key is None) ^ (secret_key is None):
    raise ValueError("both access key and secret key must be provided")
elif access_key == "" or secret_key == "":
    raise ValueError("access key or access key must not be empty")
```

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_update(self,
Rename this method as `update_service_account`

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +                               status: str | None = None) -> str:
Add return type

2024-02-22 01:58 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_delete(self, access_key) -> str:
1. add parameter typing
2. rename this method as `delete_service_account`

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_info(self, access_key):
```suggestion
    def get_service_account_info(self, access_key: str) -> str:
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_list(self, user: str):
```suggestion
    def list_service_account(self, user: str) -> str:
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +                            secret_key: str = "",
```suggestion
                            access_key: str | None = None,
                            secret_key: str | None = None,
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_add(self,
```suggestion
    def add_service_account(self,
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +                             "given and vice versa")
```suggestion
        if (access_key is None) ^ (secret_key is None):
            raise ValueError("both access key and secret key must be provided")
        elif access_key == "" or secret_key == "":
            raise ValueError("access key or access key must not be empty")
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_update(self,
```suggestion
    def update_service_account(self,
```

2024-02-22 06:48 UTC, balamurugana commented on minio/minioadmin.py
> +    def service_account_delete(self, access_key) -> str:
```suggestion
    def delete_service_account(self, access_key: str) -> str:
```

2024-02-22 06:51 UTC, balamurugana commented on minio/minioadmin.py
> +                            status: str | None = None):
```suggestion
                            status: str | None = None) -> str:
```

2024-02-22 06:53 UTC, balamurugana commented on minio/minioadmin.py
> +        elif access_key == "" or secret_key == "":
```suggestion
        if access_key == "" or secret_key == "":
```

2024-02-22 07:05 UTC, balamurugana commented on minio/minioadmin.py
> +            query_params={"accessKey": access_key},
```suggestion
```

2024-02-22 07:12 UTC, balamurugana commented on minio/minioadmin.py
> +    def get_service_account_info(self, access_key: str) -> str:
```suggestion
    def get_service_account(self, access_key: str) -> str:
```

2024-02-22 07:15 UTC, balamurugana approved these changes

2024-02-22 08:56 UTC, harshavardhana approved these changes

2024-02-22 08:56 UTC, merged