prompt_object API support
minio/minio-py pull request #1450
Opened 2024-10-24 22:44 UTC by dilverse

2024-10-24 22:46 UTC, harshavardhana requested changes

2024-10-24 22:46 UTC, harshavardhana commented on minio/api.py
> +        # print(response.status, response.data.decode())
```suggestion
```

2024-10-24 22:48 UTC, harshavardhana approved these changes

2024-10-25 03:10 UTC, balamurugana approved these changes

2024-10-25 14:43 UTC, harshavardhana approved these changes

2024-10-25 14:43 UTC, merged