:sparkles: Add account info admin command
minio/minio-py pull request #1463
Opened 2024-12-05 14:27 UTC by mhkarimi1383

Account info admin command was missing in admin client and needed to get bucket information (just like what we have in console)

2025-01-06 13:04 UTC, harshavardhana submitted a review, later dismissed

2025-01-19 08:59 UTC, minio-trusted commented
PTAL @balamurugana

2025-01-19 09:58 UTC, balamurugana requested changes

2025-01-19 09:58 UTC, balamurugana commented on minio/minioadmin.py
> +    def account_info(self) -> str:
Refer https://github.com/minio/madmin-go/blob/main/user-commands.go#L80
1. Add comment as per `madmin-go`
2. Add argument `prefix_usage: bool = false` and handle it

2025-01-19 15:15 UTC, mhkarimi1383 commented on minio/minioadmin.py
> +    def account_info(self) -> str:
Fixed.

2025-01-19 15:47 UTC, balamurugana requested changes

2025-01-19 15:47 UTC, balamurugana commented on minio/minioadmin.py
> +            query_params={
Send `query_params` only if `prefix_usage` is `true`

2025-01-19 15:53 UTC, mhkarimi1383 commented on minio/minioadmin.py
> +            query_params={
Fixed, Also switched to Mapping in _url_open for query params to avoid further type errors

2025-01-19 16:12 UTC, balamurugana requested changes

2025-01-19 16:12 UTC, balamurugana commented on minio/minioadmin.py
> +            query_params: Mapping | None = None,
Do not change `DictType`. It is valid!

2025-01-19 16:12 UTC, balamurugana commented on minio/minioadmin.py
> +            }
```suggestion
```

2025-01-19 16:12 UTC, balamurugana commented on minio/minioadmin.py
> +            query_params=query_params,
```suggestion
            query_params={"prefix_usage": "true"} if prefix_usage else None,
```

2025-01-19 16:14 UTC, mhkarimi1383 commented on minio/minioadmin.py
> +            query_params: Mapping | None = None,
My IDE says that using mapping is correct :)

Since the type of dict is dynamic

2025-01-19 16:19 UTC, balamurugana commented on minio/minioadmin.py
> +            query_params: Mapping | None = None,
https://github.com/minio/minio-py/blob/master/minio/helpers.py#L82 is what we want.

2025-01-19 16:21 UTC, mhkarimi1383 commented on minio/minioadmin.py
> +            query_params: Mapping | None = None,
Fixed

2025-01-19 23:14 UTC, harshavardhana approved these changes

2025-01-19 23:14 UTC, merged