Allow to pass region to IamAwsProvider
minio/minio-py pull request #999
Opened 2020-10-14 09:40 UTC by dtaniwaki

I use a different environment variable from `AWS_REGION` and the Minio client accepts it because it receives the value via the arguments. I think we can allow it to `IamAwsProvider` too.

2020-10-14 20:56 UTC, balamurugana requested changes
This is not the way IAM roles work in Amazon EC2/ECS environment. In the environment, all necessary ENV VARS are populated.

2020-10-15 01:57 UTC, dtaniwaki commented
Should I just set `custom_endpoint` with the region?

2020-10-15 01:58 UTC, dtaniwaki commented
`AWS_REGION` is not set in my EKS automatically.

2020-10-15 04:52 UTC, balamurugana commented
@dtaniwaki 

> `AWS_REGION` is not set in my EKS automatically.

This means you don't need region to access your STS service. I don't see this PR useful.

2020-10-15 04:59 UTC, dtaniwaki commented
Ah, I understand what happened.

https://github.com/minio/minio-py/blob/316c3243f5393236667a48a337481db1ba9c6f0d/minio/credentials/providers.py#L421-L423

The format function prints `None` if it's None and makes the URL invalid.

2020-10-15 05:03 UTC, dtaniwaki commented
Made another PR https://github.com/minio/minio-py/pull/1001 and closing this one.

2020-10-15 05:03 UTC, closed without merging